services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    user: 1000:1000
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mariadb
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - data:/var/lib/mysql
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
  